# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UserRoleManagementDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_UserRoleManagementDialog(object):
    def setupUi(self, UserRoleManagementDialog):
        UserRoleManagementDialog.setObjectName(_fromUtf8("UserRoleManagementDialog"))
        UserRoleManagementDialog.resize(850, 550)
        UserRoleManagementDialog.setMinimumSize(QtCore.QSize(850, 550))
        UserRoleManagementDialog.setMaximumSize(QtCore.QSize(850, 550))
        UserRoleManagementDialog.setBaseSize(QtCore.QSize(860, 550))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/user_role_management.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UserRoleManagementDialog.setWindowIcon(icon)
        self.line = QtGui.QFrame(UserRoleManagementDialog)
        self.line.setGeometry(QtCore.QRect(0, 20, 798, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_9 = QtGui.QLabel(UserRoleManagementDialog)
        self.label_9.setGeometry(QtCore.QRect(10, 7, 231, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.close_button = QtGui.QPushButton(UserRoleManagementDialog)
        self.close_button.setGeometry(QtCore.QRect(730, 500, 70, 23))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.help_button = QtGui.QPushButton(UserRoleManagementDialog)
        self.help_button.setGeometry(QtCore.QRect(10, 500, 81, 23))
        self.help_button.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/help_button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help_button.setIcon(icon1)
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.line_2 = QtGui.QFrame(UserRoleManagementDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 530, 799, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.username_real_lbl = QtGui.QLabel(UserRoleManagementDialog)
        self.username_real_lbl.setGeometry(QtCore.QRect(220, 7, 121, 16))
        self.username_real_lbl.setText(_fromUtf8(""))
        self.username_real_lbl.setObjectName(_fromUtf8("username_real_lbl"))
        self.tabWidget = QtGui.QTabWidget(UserRoleManagementDialog)
        self.tabWidget.setGeometry(QtCore.QRect(8, 30, 833, 461))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.user_register_tab = QtGui.QWidget()
        self.user_register_tab.setObjectName(_fromUtf8("user_register_tab"))
        self.groupBox = QtGui.QGroupBox(self.user_register_tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 2, 331, 399))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.username_edit = QtGui.QLineEdit(self.groupBox)
        self.username_edit.setGeometry(QtCore.QRect(10, 30, 150, 20))
        self.username_edit.setObjectName(_fromUtf8("username_edit"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 13, 151, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.password_edit = QtGui.QLineEdit(self.groupBox)
        self.password_edit.setGeometry(QtCore.QRect(10, 67, 150, 20))
        self.password_edit.setEchoMode(QtGui.QLineEdit.Password)
        self.password_edit.setObjectName(_fromUtf8("password_edit"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 151, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 151, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.retype_password_edit = QtGui.QLineEdit(self.groupBox)
        self.retype_password_edit.setGeometry(QtCore.QRect(10, 107, 150, 20))
        self.retype_password_edit.setEchoMode(QtGui.QLineEdit.Password)
        self.retype_password_edit.setObjectName(_fromUtf8("retype_password_edit"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(170, 13, 151, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.surname_edit = QtGui.QLineEdit(self.groupBox)
        self.surname_edit.setGeometry(QtCore.QRect(170, 30, 150, 20))
        self.surname_edit.setObjectName(_fromUtf8("surname_edit"))
        self.firstname_edit = QtGui.QLineEdit(self.groupBox)
        self.firstname_edit.setGeometry(QtCore.QRect(170, 67, 150, 20))
        self.firstname_edit.setObjectName(_fromUtf8("firstname_edit"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(170, 50, 151, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 204, 151, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.add_button = QtGui.QPushButton(self.groupBox)
        self.add_button.setGeometry(QtCore.QRect(31, 250, 70, 23))
        self.add_button.setObjectName(_fromUtf8("add_button"))
        self.update_button = QtGui.QPushButton(self.groupBox)
        self.update_button.setGeometry(QtCore.QRect(131, 250, 70, 23))
        self.update_button.setObjectName(_fromUtf8("update_button"))
        self.delete_button = QtGui.QPushButton(self.groupBox)
        self.delete_button.setGeometry(QtCore.QRect(228, 250, 70, 23))
        self.delete_button.setObjectName(_fromUtf8("delete_button"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 276, 311, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(170, 90, 151, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.phone_edit = QtGui.QLineEdit(self.groupBox)
        self.phone_edit.setGeometry(QtCore.QRect(170, 107, 150, 20))
        self.phone_edit.setText(_fromUtf8(""))
        self.phone_edit.setObjectName(_fromUtf8("phone_edit"))
        self.user_role_lwidget = QtGui.QListWidget(self.groupBox)
        self.user_role_lwidget.setGeometry(QtCore.QRect(10, 292, 311, 75))
        self.user_role_lwidget.setObjectName(_fromUtf8("user_role_lwidget"))
        self.position_cbox = QtGui.QComboBox(self.groupBox)
        self.position_cbox.setGeometry(QtCore.QRect(10, 223, 311, 22))
        self.position_cbox.setObjectName(_fromUtf8("position_cbox"))
        self.mac_address_edit = QtGui.QLineEdit(self.groupBox)
        self.mac_address_edit.setGeometry(QtCore.QRect(170, 147, 151, 20))
        self.mac_address_edit.setObjectName(_fromUtf8("mac_address_edit"))
        self.register_edit = QtGui.QLineEdit(self.groupBox)
        self.register_edit.setGeometry(QtCore.QRect(10, 147, 151, 20))
        self.register_edit.setObjectName(_fromUtf8("register_edit"))
        self.label_17 = QtGui.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(10, 129, 151, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.settings_button = QtGui.QPushButton(self.groupBox)
        self.settings_button.setGeometry(QtCore.QRect(50, 371, 221, 23))
        self.settings_button.setObjectName(_fromUtf8("settings_button"))
        self.get_mac_checkbox = QtGui.QCheckBox(self.groupBox)
        self.get_mac_checkbox.setGeometry(QtCore.QRect(170, 128, 141, 20))
        self.get_mac_checkbox.setObjectName(_fromUtf8("get_mac_checkbox"))
        self.label_18 = QtGui.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(10, 167, 151, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.email_edit = QtGui.QLineEdit(self.groupBox)
        self.email_edit.setGeometry(QtCore.QRect(10, 184, 311, 20))
        self.email_edit.setObjectName(_fromUtf8("email_edit"))
        self.groupBox_3 = QtGui.QGroupBox(self.user_register_tab)
        self.groupBox_3.setGeometry(QtCore.QRect(350, 10, 230, 391))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 15, 201, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.down_groups_button = QtGui.QPushButton(self.groupBox_3)
        self.down_groups_button.setGeometry(QtCore.QRect(70, 187, 30, 25))
        self.down_groups_button.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/down_button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.down_groups_button.setIcon(icon2)
        self.down_groups_button.setObjectName(_fromUtf8("down_groups_button"))
        self.up_groups_button = QtGui.QPushButton(self.groupBox_3)
        self.up_groups_button.setGeometry(QtCore.QRect(116, 187, 30, 25))
        self.up_groups_button.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/up_button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.up_groups_button.setIcon(icon3)
        self.up_groups_button.setObjectName(_fromUtf8("up_groups_button"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(10, 215, 209, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.group_lwidget = QtGui.QListWidget(self.groupBox_3)
        self.group_lwidget.setGeometry(QtCore.QRect(10, 31, 211, 151))
        self.group_lwidget.setObjectName(_fromUtf8("group_lwidget"))
        self.member_lwidget = QtGui.QListWidget(self.groupBox_3)
        self.member_lwidget.setGeometry(QtCore.QRect(10, 233, 211, 151))
        self.member_lwidget.setObjectName(_fromUtf8("member_lwidget"))
        self.groupBox_7 = QtGui.QGroupBox(self.user_register_tab)
        self.groupBox_7.setGeometry(QtCore.QRect(590, 10, 204, 391))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        self.label_14.setGeometry(QtCore.QRect(15, 16, 181, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.aimag_cbox = QtGui.QComboBox(self.groupBox_7)
        self.aimag_cbox.setGeometry(QtCore.QRect(10, 33, 184, 22))
        self.aimag_cbox.setObjectName(_fromUtf8("aimag_cbox"))
        self.aimag_lwidget = QtGui.QListWidget(self.groupBox_7)
        self.aimag_lwidget.setGeometry(QtCore.QRect(10, 109, 184, 82))
        self.aimag_lwidget.setObjectName(_fromUtf8("aimag_lwidget"))
        self.down_aimag_button = QtGui.QPushButton(self.groupBox_7)
        self.down_aimag_button.setGeometry(QtCore.QRect(64, 64, 30, 25))
        self.down_aimag_button.setText(_fromUtf8(""))
        self.down_aimag_button.setIcon(icon2)
        self.down_aimag_button.setObjectName(_fromUtf8("down_aimag_button"))
        self.up_aimag_button = QtGui.QPushButton(self.groupBox_7)
        self.up_aimag_button.setGeometry(QtCore.QRect(110, 64, 30, 25))
        self.up_aimag_button.setText(_fromUtf8(""))
        self.up_aimag_button.setIcon(icon3)
        self.up_aimag_button.setObjectName(_fromUtf8("up_aimag_button"))
        self.label_16 = QtGui.QLabel(self.groupBox_7)
        self.label_16.setGeometry(QtCore.QRect(15, 192, 181, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.soum_cbox = QtGui.QComboBox(self.groupBox_7)
        self.soum_cbox.setGeometry(QtCore.QRect(10, 207, 184, 22))
        self.soum_cbox.setObjectName(_fromUtf8("soum_cbox"))
        self.soum_lwidget = QtGui.QListWidget(self.groupBox_7)
        self.soum_lwidget.setGeometry(QtCore.QRect(10, 280, 184, 102))
        self.soum_lwidget.setObjectName(_fromUtf8("soum_lwidget"))
        self.up_soum_button = QtGui.QPushButton(self.groupBox_7)
        self.up_soum_button.setGeometry(QtCore.QRect(110, 235, 30, 25))
        self.up_soum_button.setText(_fromUtf8(""))
        self.up_soum_button.setIcon(icon3)
        self.up_soum_button.setObjectName(_fromUtf8("up_soum_button"))
        self.down_soum_button = QtGui.QPushButton(self.groupBox_7)
        self.down_soum_button.setGeometry(QtCore.QRect(64, 235, 30, 25))
        self.down_soum_button.setText(_fromUtf8(""))
        self.down_soum_button.setIcon(icon2)
        self.down_soum_button.setObjectName(_fromUtf8("down_soum_button"))
        self.label_30 = QtGui.QLabel(self.groupBox_7)
        self.label_30.setGeometry(QtCore.QRect(10, 90, 181, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_4 = QtGui.QLabel(self.groupBox_7)
        self.label_4.setGeometry(QtCore.QRect(10, 260, 181, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.tabWidget.addTab(self.user_register_tab, _fromUtf8(""))
        self.user_management_tab = QtGui.QWidget()
        self.user_management_tab.setObjectName(_fromUtf8("user_management_tab"))
        self.user_twidget = QtGui.QTableWidget(self.user_management_tab)
        self.user_twidget.setGeometry(QtCore.QRect(10, 40, 181, 281))
        self.user_twidget.setObjectName(_fromUtf8("user_twidget"))
        self.user_twidget.setColumnCount(1)
        self.user_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.user_twidget.setHorizontalHeaderItem(0, item)
        self.user_twidget.horizontalHeader().setDefaultSectionSize(200)
        self.position_twidget = QtGui.QTableWidget(self.user_management_tab)
        self.position_twidget.setGeometry(QtCore.QRect(199, 40, 221, 281))
        self.position_twidget.setObjectName(_fromUtf8("position_twidget"))
        self.position_twidget.setColumnCount(1)
        self.position_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.position_twidget.setHorizontalHeaderItem(0, item)
        self.position_twidget.horizontalHeader().setDefaultSectionSize(250)
        self.right_grud_twidget = QtGui.QTableWidget(self.user_management_tab)
        self.right_grud_twidget.setGeometry(QtCore.QRect(430, 40, 391, 281))
        self.right_grud_twidget.setObjectName(_fromUtf8("right_grud_twidget"))
        self.right_grud_twidget.setColumnCount(5)
        self.right_grud_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.right_grud_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.right_grud_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.right_grud_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.right_grud_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.right_grud_twidget.setHorizontalHeaderItem(4, item)
        self.groupBox_2 = QtGui.QGroupBox(self.user_management_tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 330, 811, 85))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.load_default_settings_button = QtGui.QPushButton(self.user_management_tab)
        self.load_default_settings_button.setGeometry(QtCore.QRect(650, 10, 171, 23))
        self.load_default_settings_button.setObjectName(_fromUtf8("load_default_settings_button"))
        self.load_users_button = QtGui.QPushButton(self.user_management_tab)
        self.load_users_button.setGeometry(QtCore.QRect(9, 10, 171, 23))
        self.load_users_button.setObjectName(_fromUtf8("load_users_button"))
        self.load_position_button = QtGui.QPushButton(self.user_management_tab)
        self.load_position_button.setGeometry(QtCore.QRect(199, 10, 171, 23))
        self.load_position_button.setObjectName(_fromUtf8("load_position_button"))
        self.tabWidget.addTab(self.user_management_tab, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.settings_right_grud_twidget = QtGui.QTableWidget(self.tab)
        self.settings_right_grud_twidget.setGeometry(QtCore.QRect(270, 20, 551, 391))
        self.settings_right_grud_twidget.setObjectName(_fromUtf8("settings_right_grud_twidget"))
        self.settings_right_grud_twidget.setColumnCount(6)
        self.settings_right_grud_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.settings_right_grud_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.settings_right_grud_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.settings_right_grud_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.settings_right_grud_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.settings_right_grud_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.settings_right_grud_twidget.setHorizontalHeaderItem(5, item)
        self.settings_position_twidget = QtGui.QTableWidget(self.tab)
        self.settings_position_twidget.setGeometry(QtCore.QRect(10, 20, 251, 391))
        self.settings_position_twidget.setObjectName(_fromUtf8("settings_position_twidget"))
        self.settings_position_twidget.setColumnCount(1)
        self.settings_position_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.settings_position_twidget.setHorizontalHeaderItem(0, item)
        self.settings_position_twidget.horizontalHeader().setDefaultSectionSize(250)
        self.settings_position_twidget.horizontalHeader().setMinimumSectionSize(33)
        self.settings_position_twidget.verticalHeader().setDefaultSectionSize(30)
        self.settings_position_twidget.verticalHeader().setMinimumSectionSize(19)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.refresh_button = QtGui.QPushButton(UserRoleManagementDialog)
        self.refresh_button.setGeometry(QtCore.QRect(550, 500, 70, 23))
        self.refresh_button.setObjectName(_fromUtf8("refresh_button"))
        self.apply_button = QtGui.QPushButton(UserRoleManagementDialog)
        self.apply_button.setGeometry(QtCore.QRect(640, 500, 70, 23))
        self.apply_button.setObjectName(_fromUtf8("apply_button"))
        self.status_label = QtGui.QLabel(UserRoleManagementDialog)
        self.status_label.setGeometry(QtCore.QRect(100, 500, 440, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setBold(True)
        font.setWeight(75)
        self.status_label.setFont(font)
        self.status_label.setObjectName(_fromUtf8("status_label"))

        self.retranslateUi(UserRoleManagementDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(UserRoleManagementDialog)
        UserRoleManagementDialog.setTabOrder(self.help_button, self.close_button)

    def retranslateUi(self, UserRoleManagementDialog):
        UserRoleManagementDialog.setWindowTitle(_translate("UserRoleManagementDialog", "User Role Management", None))
        self.label_9.setText(_translate("UserRoleManagementDialog", "User Role Management", None))
        self.close_button.setText(_translate("UserRoleManagementDialog", "Close", None))
        self.groupBox.setTitle(_translate("UserRoleManagementDialog", "User Roles", None))
        self.label.setText(_translate("UserRoleManagementDialog", "User Name", None))
        self.label_2.setText(_translate("UserRoleManagementDialog", "Password", None))
        self.label_3.setText(_translate("UserRoleManagementDialog", "Retype Password", None))
        self.label_5.setText(_translate("UserRoleManagementDialog", "Surname", None))
        self.label_6.setText(_translate("UserRoleManagementDialog", "First Name", None))
        self.label_7.setText(_translate("UserRoleManagementDialog", "Position", None))
        self.add_button.setText(_translate("UserRoleManagementDialog", "Add", None))
        self.update_button.setText(_translate("UserRoleManagementDialog", "Update", None))
        self.delete_button.setText(_translate("UserRoleManagementDialog", "Delete", None))
        self.label_8.setText(_translate("UserRoleManagementDialog", "Existing User Roles", None))
        self.label_15.setText(_translate("UserRoleManagementDialog", "Phone", None))
        self.label_17.setText(_translate("UserRoleManagementDialog", "Register", None))
        self.settings_button.setText(_translate("UserRoleManagementDialog", "User Settings", None))
        self.get_mac_checkbox.setText(_translate("UserRoleManagementDialog", "MAC Address(es)", None))
        self.label_18.setText(_translate("UserRoleManagementDialog", "Email", None))
        self.groupBox_3.setTitle(_translate("UserRoleManagementDialog", "Groups", None))
        self.label_12.setText(_translate("UserRoleManagementDialog", "Groups Available", None))
        self.label_13.setText(_translate("UserRoleManagementDialog", "Groups the user is a member of", None))
        self.groupBox_7.setTitle(_translate("UserRoleManagementDialog", "Spatial Restrictions", None))
        self.label_14.setText(_translate("UserRoleManagementDialog", "Aimag / Duureg", None))
        self.label_16.setText(_translate("UserRoleManagementDialog", "Soum", None))
        self.label_30.setText(_translate("UserRoleManagementDialog", "Granted Aimags / Duuregs", None))
        self.label_4.setText(_translate("UserRoleManagementDialog", "Granted Soums", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.user_register_tab), _translate("UserRoleManagementDialog", "User Register", None))
        item = self.user_twidget.horizontalHeaderItem(0)
        item.setText(_translate("UserRoleManagementDialog", "Employeer", None))
        item = self.position_twidget.horizontalHeaderItem(0)
        item.setText(_translate("UserRoleManagementDialog", "Position", None))
        item = self.right_grud_twidget.horizontalHeaderItem(0)
        item.setText(_translate("UserRoleManagementDialog", "Rigth type", None))
        item = self.right_grud_twidget.horizontalHeaderItem(1)
        item.setText(_translate("UserRoleManagementDialog", "View", None))
        item = self.right_grud_twidget.horizontalHeaderItem(2)
        item.setText(_translate("UserRoleManagementDialog", "Add", None))
        item = self.right_grud_twidget.horizontalHeaderItem(3)
        item.setText(_translate("UserRoleManagementDialog", "Delete", None))
        item = self.right_grud_twidget.horizontalHeaderItem(4)
        item.setText(_translate("UserRoleManagementDialog", "Edit", None))
        self.groupBox_2.setTitle(_translate("UserRoleManagementDialog", "Employeer Details", None))
        self.load_default_settings_button.setText(_translate("UserRoleManagementDialog", "Load Default Settings", None))
        self.load_users_button.setText(_translate("UserRoleManagementDialog", "Load All Users", None))
        self.load_position_button.setText(_translate("UserRoleManagementDialog", "Load All Position", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.user_management_tab), _translate("UserRoleManagementDialog", "User Management", None))
        item = self.settings_right_grud_twidget.horizontalHeaderItem(0)
        item.setText(_translate("UserRoleManagementDialog", "Right Type English", None))
        item = self.settings_right_grud_twidget.horizontalHeaderItem(1)
        item.setText(_translate("UserRoleManagementDialog", "Right Type Mongolia", None))
        item = self.settings_right_grud_twidget.horizontalHeaderItem(2)
        item.setText(_translate("UserRoleManagementDialog", "View", None))
        item = self.settings_right_grud_twidget.horizontalHeaderItem(3)
        item.setText(_translate("UserRoleManagementDialog", "Add", None))
        item = self.settings_right_grud_twidget.horizontalHeaderItem(4)
        item.setText(_translate("UserRoleManagementDialog", "Delete", None))
        item = self.settings_right_grud_twidget.horizontalHeaderItem(5)
        item.setText(_translate("UserRoleManagementDialog", "Edit", None))
        item = self.settings_position_twidget.horizontalHeaderItem(0)
        item.setText(_translate("UserRoleManagementDialog", "Position", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("UserRoleManagementDialog", "Right Settings", None))
        self.refresh_button.setText(_translate("UserRoleManagementDialog", "Refresh", None))
        self.apply_button.setText(_translate("UserRoleManagementDialog", "Save", None))
        self.status_label.setText(_translate("UserRoleManagementDialog", "Messages", None))

import resources_rc
