# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\WebgisUtilityDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WebgisUtilityDialog(object):
    def setupUi(self, WebgisUtilityDialog):
        WebgisUtilityDialog.setObjectName(_fromUtf8("WebgisUtilityDialog"))
        WebgisUtilityDialog.resize(686, 434)
        WebgisUtilityDialog.setMinimumSize(QtCore.QSize(686, 434))
        WebgisUtilityDialog.setMaximumSize(QtCore.QSize(686, 434))
        self.webgis_ip_edit = QtGui.QLineEdit(WebgisUtilityDialog)
        self.webgis_ip_edit.setEnabled(False)
        self.webgis_ip_edit.setGeometry(QtCore.QRect(150, 37, 127, 20))
        self.webgis_ip_edit.setReadOnly(True)
        self.webgis_ip_edit.setObjectName(_fromUtf8("webgis_ip_edit"))
        self.line = QtGui.QFrame(WebgisUtilityDialog)
        self.line.setGeometry(QtCore.QRect(3, 18, 681, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.person_id = QtGui.QLineEdit(WebgisUtilityDialog)
        self.person_id.setGeometry(QtCore.QRect(150, 130, 127, 20))
        self.person_id.setObjectName(_fromUtf8("person_id"))
        self.label = QtGui.QLabel(WebgisUtilityDialog)
        self.label.setGeometry(QtCore.QRect(20, 132, 131, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.refresh_webgis_button = QtGui.QPushButton(WebgisUtilityDialog)
        self.refresh_webgis_button.setEnabled(False)
        self.refresh_webgis_button.setGeometry(QtCore.QRect(10, 400, 91, 23))
        self.refresh_webgis_button.setObjectName(_fromUtf8("refresh_webgis_button"))
        self.find_ownership_button = QtGui.QPushButton(WebgisUtilityDialog)
        self.find_ownership_button.setEnabled(False)
        self.find_ownership_button.setGeometry(QtCore.QRect(149, 155, 128, 23))
        self.find_ownership_button.setObjectName(_fromUtf8("find_ownership_button"))
        self.groupBox = QtGui.QGroupBox(WebgisUtilityDialog)
        self.groupBox.setGeometry(QtCore.QRect(5, 179, 676, 153))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.owner_twidget = QtGui.QTableWidget(self.groupBox)
        self.owner_twidget.setGeometry(QtCore.QRect(4, 14, 669, 131))
        self.owner_twidget.setObjectName(_fromUtf8("owner_twidget"))
        self.owner_twidget.setColumnCount(5)
        self.owner_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.owner_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.owner_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.owner_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.owner_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.owner_twidget.setHorizontalHeaderItem(4, item)
        self.owner_twidget.horizontalHeader().setDefaultSectionSize(180)
        self.owner_twidget.horizontalHeader().setMinimumSectionSize(30)
        self.owner_twidget.verticalHeader().setDefaultSectionSize(30)
        self.owner_twidget.verticalHeader().setMinimumSectionSize(19)
        self.detail_print_button = QtGui.QPushButton(WebgisUtilityDialog)
        self.detail_print_button.setEnabled(True)
        self.detail_print_button.setGeometry(QtCore.QRect(537, 365, 141, 23))
        self.detail_print_button.setObjectName(_fromUtf8("detail_print_button"))
        self.close_button = QtGui.QPushButton(WebgisUtilityDialog)
        self.close_button.setGeometry(QtCore.QRect(597, 399, 75, 23))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.line_2 = QtGui.QFrame(WebgisUtilityDialog)
        self.line_2.setGeometry(QtCore.QRect(1, 386, 681, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.open_webgis_button = QtGui.QPushButton(WebgisUtilityDialog)
        self.open_webgis_button.setGeometry(QtCore.QRect(324, 358, 111, 23))
        self.open_webgis_button.setObjectName(_fromUtf8("open_webgis_button"))
        self.webgis_url_edit = QtGui.QLineEdit(WebgisUtilityDialog)
        self.webgis_url_edit.setGeometry(QtCore.QRect(20, 359, 290, 20))
        self.webgis_url_edit.setReadOnly(True)
        self.webgis_url_edit.setObjectName(_fromUtf8("webgis_url_edit"))
        self.label_2 = QtGui.QLabel(WebgisUtilityDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 338, 291, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.error_label = QtGui.QLabel(WebgisUtilityDialog)
        self.error_label.setGeometry(QtCore.QRect(110, 400, 471, 20))
        self.error_label.setText(_fromUtf8(""))
        self.error_label.setObjectName(_fromUtf8("error_label"))
        self.label_3 = QtGui.QLabel(WebgisUtilityDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 6, 211, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.progressBar = QtGui.QProgressBar(WebgisUtilityDialog)
        self.progressBar.setGeometry(QtCore.QRect(390, 7, 291, 13))
        self.progressBar.setProperty("value", 1)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.check_connect_button = QtGui.QPushButton(WebgisUtilityDialog)
        self.check_connect_button.setGeometry(QtCore.QRect(10, 36, 134, 23))
        self.check_connect_button.setObjectName(_fromUtf8("check_connect_button"))
        self.label_4 = QtGui.QLabel(WebgisUtilityDialog)
        self.label_4.setGeometry(QtCore.QRect(230, 6, 143, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lm_rbutton = QtGui.QRadioButton(WebgisUtilityDialog)
        self.lm_rbutton.setGeometry(QtCore.QRect(20, 70, 82, 17))
        self.lm_rbutton.setObjectName(_fromUtf8("lm_rbutton"))
        self.lpis_rbutton = QtGui.QRadioButton(WebgisUtilityDialog)
        self.lpis_rbutton.setGeometry(QtCore.QRect(20, 90, 82, 17))
        self.lpis_rbutton.setObjectName(_fromUtf8("lpis_rbutton"))
        self.subject_rbutton = QtGui.QRadioButton(WebgisUtilityDialog)
        self.subject_rbutton.setGeometry(QtCore.QRect(20, 110, 82, 17))
        self.subject_rbutton.setObjectName(_fromUtf8("subject_rbutton"))
        self.groupBox_2 = QtGui.QGroupBox(WebgisUtilityDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(300, 30, 381, 149))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.owner_co_twidget = QtGui.QTableWidget(self.groupBox_2)
        self.owner_co_twidget.setGeometry(QtCore.QRect(7, 15, 371, 128))
        self.owner_co_twidget.setObjectName(_fromUtf8("owner_co_twidget"))
        self.owner_co_twidget.setColumnCount(5)
        self.owner_co_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.owner_co_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.owner_co_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.owner_co_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.owner_co_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.owner_co_twidget.setHorizontalHeaderItem(4, item)
        self.owner_co_twidget.horizontalHeader().setDefaultSectionSize(120)
        self.defination_print_button = QtGui.QPushButton(WebgisUtilityDialog)
        self.defination_print_button.setEnabled(True)
        self.defination_print_button.setGeometry(QtCore.QRect(537, 335, 141, 23))
        self.defination_print_button.setObjectName(_fromUtf8("defination_print_button"))

        self.retranslateUi(WebgisUtilityDialog)
        QtCore.QMetaObject.connectSlotsByName(WebgisUtilityDialog)
        WebgisUtilityDialog.setTabOrder(self.person_id, self.find_ownership_button)
        WebgisUtilityDialog.setTabOrder(self.find_ownership_button, self.open_webgis_button)
        WebgisUtilityDialog.setTabOrder(self.open_webgis_button, self.owner_twidget)
        WebgisUtilityDialog.setTabOrder(self.owner_twidget, self.webgis_ip_edit)
        WebgisUtilityDialog.setTabOrder(self.webgis_ip_edit, self.refresh_webgis_button)
        WebgisUtilityDialog.setTabOrder(self.refresh_webgis_button, self.webgis_url_edit)
        WebgisUtilityDialog.setTabOrder(self.webgis_url_edit, self.detail_print_button)
        WebgisUtilityDialog.setTabOrder(self.detail_print_button, self.close_button)

    def retranslateUi(self, WebgisUtilityDialog):
        WebgisUtilityDialog.setWindowTitle(_translate("WebgisUtilityDialog", "Dialog", None))
        self.label.setText(_translate("WebgisUtilityDialog", "Регистрийн дугаар:", None))
        self.refresh_webgis_button.setText(_translate("WebgisUtilityDialog", "Refresh WebGIS", None))
        self.find_ownership_button.setText(_translate("WebgisUtilityDialog", "Find Ownership", None))
        self.groupBox.setTitle(_translate("WebgisUtilityDialog", "Parcel information", None))
        item = self.owner_twidget.horizontalHeaderItem(0)
        item.setText(_translate("WebgisUtilityDialog", "Parcel ID", None))
        item = self.owner_twidget.horizontalHeaderItem(1)
        item.setText(_translate("WebgisUtilityDialog", "Person information", None))
        item = self.owner_twidget.horizontalHeaderItem(2)
        item.setText(_translate("WebgisUtilityDialog", "Legal inforamation", None))
        item = self.owner_twidget.horizontalHeaderItem(3)
        item.setText(_translate("WebgisUtilityDialog", "Address", None))
        item = self.owner_twidget.horizontalHeaderItem(4)
        item.setText(_translate("WebgisUtilityDialog", "Status", None))
        self.detail_print_button.setText(_translate("WebgisUtilityDialog", "Detail Pring", None))
        self.close_button.setText(_translate("WebgisUtilityDialog", "Close", None))
        self.open_webgis_button.setText(_translate("WebgisUtilityDialog", "Open WebGIS", None))
        self.label_2.setText(_translate("WebgisUtilityDialog", "WebGIS Address", None))
        self.label_3.setText(_translate("WebgisUtilityDialog", "WebGIS Utility", None))
        self.check_connect_button.setText(_translate("WebgisUtilityDialog", "Connect to WebGIS", None))
        self.label_4.setText(_translate("WebgisUtilityDialog", "Find ownership progress:", None))
        self.lm_rbutton.setText(_translate("WebgisUtilityDialog", "LM", None))
        self.lpis_rbutton.setText(_translate("WebgisUtilityDialog", "LPIS", None))
        self.subject_rbutton.setText(_translate("WebgisUtilityDialog", "Subject", None))
        self.groupBox_2.setTitle(_translate("WebgisUtilityDialog", "Information Detail", None))
        item = self.owner_co_twidget.horizontalHeaderItem(0)
        item.setText(_translate("WebgisUtilityDialog", "Person ID", None))
        item = self.owner_co_twidget.horizontalHeaderItem(1)
        item.setText(_translate("WebgisUtilityDialog", "Person Info", None))
        item = self.owner_co_twidget.horizontalHeaderItem(2)
        item.setText(_translate("WebgisUtilityDialog", "Who", None))
        item = self.owner_co_twidget.horizontalHeaderItem(3)
        item.setText(_translate("WebgisUtilityDialog", "New Column", None))
        item = self.owner_co_twidget.horizontalHeaderItem(4)
        item.setText(_translate("WebgisUtilityDialog", "New Column", None))
        self.defination_print_button.setText(_translate("WebgisUtilityDialog", "Defination Print", None))

