# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\WebgisUtilityDialog.ui'
#
# Created: Wed Sep 28 15:04:37 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WebgisUtilityDialog(object):
    def setupUi(self, WebgisUtilityDialog):
        WebgisUtilityDialog.setObjectName(_fromUtf8("WebgisUtilityDialog"))
        WebgisUtilityDialog.resize(686, 434)
        WebgisUtilityDialog.setMinimumSize(QtCore.QSize(686, 434))
        WebgisUtilityDialog.setMaximumSize(QtCore.QSize(686, 434))
        self.webgis_ip_edit = QtGui.QLineEdit(WebgisUtilityDialog)
        self.webgis_ip_edit.setGeometry(QtCore.QRect(20, 89, 176, 20))
        self.webgis_ip_edit.setReadOnly(True)
        self.webgis_ip_edit.setObjectName(_fromUtf8("webgis_ip_edit"))
        self.label_50 = QtGui.QLabel(WebgisUtilityDialog)
        self.label_50.setGeometry(QtCore.QRect(20, 71, 181, 16))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.line = QtGui.QFrame(WebgisUtilityDialog)
        self.line.setGeometry(QtCore.QRect(3, 18, 681, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.person_id = QtGui.QLineEdit(WebgisUtilityDialog)
        self.person_id.setGeometry(QtCore.QRect(20, 133, 176, 20))
        self.person_id.setObjectName(_fromUtf8("person_id"))
        self.label = QtGui.QLabel(WebgisUtilityDialog)
        self.label.setGeometry(QtCore.QRect(20, 116, 171, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.refresh_webgis_button = QtGui.QPushButton(WebgisUtilityDialog)
        self.refresh_webgis_button.setEnabled(False)
        self.refresh_webgis_button.setGeometry(QtCore.QRect(220, 88, 91, 23))
        self.refresh_webgis_button.setObjectName(_fromUtf8("refresh_webgis_button"))
        self.find_ownership_button = QtGui.QPushButton(WebgisUtilityDialog)
        self.find_ownership_button.setEnabled(False)
        self.find_ownership_button.setGeometry(QtCore.QRect(220, 133, 91, 23))
        self.find_ownership_button.setObjectName(_fromUtf8("find_ownership_button"))
        self.groupBox = QtGui.QGroupBox(WebgisUtilityDialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 155, 651, 161))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.owner_twidget = QtGui.QTableWidget(self.groupBox)
        self.owner_twidget.setGeometry(QtCore.QRect(6, 16, 641, 137))
        self.owner_twidget.setObjectName(_fromUtf8("owner_twidget"))
        self.owner_twidget.setColumnCount(9)
        self.owner_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.owner_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.owner_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.owner_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.owner_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.owner_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.owner_twidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.owner_twidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.owner_twidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.owner_twidget.setHorizontalHeaderItem(8, item)
        self.print_button = QtGui.QPushButton(WebgisUtilityDialog)
        self.print_button.setEnabled(False)
        self.print_button.setGeometry(QtCore.QRect(596, 321, 76, 23))
        self.print_button.setObjectName(_fromUtf8("print_button"))
        self.close_button = QtGui.QPushButton(WebgisUtilityDialog)
        self.close_button.setGeometry(QtCore.QRect(597, 399, 75, 23))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.line_2 = QtGui.QFrame(WebgisUtilityDialog)
        self.line_2.setGeometry(QtCore.QRect(1, 386, 681, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.open_webgis_button = QtGui.QPushButton(WebgisUtilityDialog)
        self.open_webgis_button.setGeometry(QtCore.QRect(324, 365, 111, 23))
        self.open_webgis_button.setObjectName(_fromUtf8("open_webgis_button"))
        self.webgis_url_edit = QtGui.QLineEdit(WebgisUtilityDialog)
        self.webgis_url_edit.setGeometry(QtCore.QRect(20, 366, 290, 20))
        self.webgis_url_edit.setReadOnly(True)
        self.webgis_url_edit.setObjectName(_fromUtf8("webgis_url_edit"))
        self.label_2 = QtGui.QLabel(WebgisUtilityDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 345, 291, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.error_label = QtGui.QLabel(WebgisUtilityDialog)
        self.error_label.setGeometry(QtCore.QRect(20, 400, 481, 16))
        self.error_label.setText(_fromUtf8(""))
        self.error_label.setObjectName(_fromUtf8("error_label"))
        self.label_3 = QtGui.QLabel(WebgisUtilityDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 6, 211, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.progressBar = QtGui.QProgressBar(WebgisUtilityDialog)
        self.progressBar.setGeometry(QtCore.QRect(390, 7, 291, 13))
        self.progressBar.setProperty("value", 1)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.check_connect_button = QtGui.QPushButton(WebgisUtilityDialog)
        self.check_connect_button.setGeometry(QtCore.QRect(19, 40, 176, 23))
        self.check_connect_button.setObjectName(_fromUtf8("check_connect_button"))
        self.label_4 = QtGui.QLabel(WebgisUtilityDialog)
        self.label_4.setGeometry(QtCore.QRect(230, 6, 143, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.soum_cbox = QtGui.QComboBox(WebgisUtilityDialog)
        self.soum_cbox.setGeometry(QtCore.QRect(400, 321, 191, 22))
        self.soum_cbox.setObjectName(_fromUtf8("soum_cbox"))
        self.aimag_cbox = QtGui.QComboBox(WebgisUtilityDialog)
        self.aimag_cbox.setGeometry(QtCore.QRect(200, 321, 191, 22))
        self.aimag_cbox.setObjectName(_fromUtf8("aimag_cbox"))
        self.label_5 = QtGui.QLabel(WebgisUtilityDialog)
        self.label_5.setGeometry(QtCore.QRect(20, 323, 171, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))

        self.retranslateUi(WebgisUtilityDialog)
        QtCore.QMetaObject.connectSlotsByName(WebgisUtilityDialog)
        WebgisUtilityDialog.setTabOrder(self.person_id, self.find_ownership_button)
        WebgisUtilityDialog.setTabOrder(self.find_ownership_button, self.open_webgis_button)
        WebgisUtilityDialog.setTabOrder(self.open_webgis_button, self.owner_twidget)
        WebgisUtilityDialog.setTabOrder(self.owner_twidget, self.webgis_ip_edit)
        WebgisUtilityDialog.setTabOrder(self.webgis_ip_edit, self.refresh_webgis_button)
        WebgisUtilityDialog.setTabOrder(self.refresh_webgis_button, self.webgis_url_edit)
        WebgisUtilityDialog.setTabOrder(self.webgis_url_edit, self.print_button)
        WebgisUtilityDialog.setTabOrder(self.print_button, self.close_button)

    def retranslateUi(self, WebgisUtilityDialog):
        WebgisUtilityDialog.setWindowTitle(_translate("WebgisUtilityDialog", "Dialog", None))
        self.label_50.setText(_translate("WebgisUtilityDialog", "Webgis IP Address", None))
        self.label.setText(_translate("WebgisUtilityDialog", "Person id", None))
        self.refresh_webgis_button.setText(_translate("WebgisUtilityDialog", "Refresh WebGIS", None))
        self.find_ownership_button.setText(_translate("WebgisUtilityDialog", "Find Ownership", None))
        self.groupBox.setTitle(_translate("WebgisUtilityDialog", "Parcel information", None))
        item = self.owner_twidget.horizontalHeaderItem(0)
        item.setText(_translate("WebgisUtilityDialog", "Parcel Id(area m2)", None))
        item = self.owner_twidget.horizontalHeaderItem(1)
        item.setText(_translate("WebgisUtilityDialog", "Aimag/Soum", None))
        item = self.owner_twidget.horizontalHeaderItem(2)
        item.setText(_translate("WebgisUtilityDialog", "Street name/Khashaa", None))
        item = self.owner_twidget.horizontalHeaderItem(3)
        item.setText(_translate("WebgisUtilityDialog", "App Type", None))
        item = self.owner_twidget.horizontalHeaderItem(4)
        item.setText(_translate("WebgisUtilityDialog", "Name", None))
        item = self.owner_twidget.horizontalHeaderItem(5)
        item.setText(_translate("WebgisUtilityDialog", "Valid from", None))
        item = self.owner_twidget.horizontalHeaderItem(6)
        item.setText(_translate("WebgisUtilityDialog", "Valid Till", None))
        item = self.owner_twidget.horizontalHeaderItem(7)
        item.setText(_translate("WebgisUtilityDialog", "Decision No", None))
        item = self.owner_twidget.horizontalHeaderItem(8)
        item.setText(_translate("WebgisUtilityDialog", "Decision Date", None))
        self.print_button.setText(_translate("WebgisUtilityDialog", "Print", None))
        self.close_button.setText(_translate("WebgisUtilityDialog", "Close", None))
        self.open_webgis_button.setText(_translate("WebgisUtilityDialog", "Open WebGIS", None))
        self.label_2.setText(_translate("WebgisUtilityDialog", "WebGIS Address", None))
        self.label_3.setText(_translate("WebgisUtilityDialog", "WebGIS Utility", None))
        self.check_connect_button.setText(_translate("WebgisUtilityDialog", "Connect to WebGIS", None))
        self.label_4.setText(_translate("WebgisUtilityDialog", "Find ownership progress:", None))
        self.label_5.setText(_translate("WebgisUtilityDialog", "To whom to may concern:", None))

